export type Locale = "en" | "hi";

export const landingCopy = {
  en: {
    nav: {
      mcq: "MCQ Practice",
      mains: "Mains Eval",
      dashboard: "Dashboard",
      leaderboard: "Leaderboard",
      chat: "AI Mentor",
    },
    authBanner: {
      title: "Sign in to track progress",
      body: "Save scores, build streaks, see your dashboard, and appear on the leaderboard.",
      cta: "Sign in",
    },
    hero: {
      badge: "Free · AI-powered · Built for every aspirant",
      title: "UPSC prep that does not cost a fortune.",
      subtitle:
        "Previous-year MCQs, Mains answer evaluation, streaks, analytics, and an UPSC-Mentor chatbot — zero fees, maximum clarity.",
      ctaPrimary: "Start practicing MCQ",
      ctaSecondary: "How it works",
    },
    features: {
      title: "Everything coaching charges lakhs for",
      items: [
        {
          title: "MCQ engine",
          body: "PYQs with subject, topic, and year filters — timed mocks and instant explanations with sources.",
        },
        {
          title: "Mains evaluation",
          body: "Structured feedback on structure, depth, keywords, and word limits — marks aligned to 10/15/20 markers.",
        },
        {
          title: "Streaks & XP",
          body: "Daily habits, badges, and weekly challenges so consistency compounds like interest.",
        },
        {
          title: "Performance dashboard",
          body: "Accuracy trends, heatmaps, time-per-question, and AI weakness detection with study nudges.",
        },
        {
          title: "UPSC AI chat Bot",
          body: "Helps you to cover your syllabus and current affairs.",
        },
        {
          title: "Your learning path",
          body: "Weekly plans from exam weightage × your gaps — revision spaced for retention.",
        },
      ],
    },
    bonus: {
      title: "Built for Bharat",
      ca: "Daily current affairs quizzes",
      analyzer: "Previous-year paper analyzer",
      prompts: "Daily Mains writing prompt",
      offline: "PWA offline MCQs",
      lang: "English + Hindi UI",
    },
    footer: "UPSCMENTOR — democratizing access. Stack: Cursor, Convex · Groq · Apify · Exa.",
    signIn: "Sign in",
    auth: {
      title: "Sign in",
      subtitle: "Use email and password, or continue with Google.",
      email: "Email",
      password: "Password",
      submitSignIn: "Sign in",
      submitSignUp: "Create account",
      toggleToSignUp: "Need an account? Sign up",
      toggleToSignIn: "Already registered? Sign in",
      google: "Continue with Google",
      signOut: "Sign out",
      configureConvex:
        "Set NEXT_PUBLIC_CONVEX_URL in .env.local and run npx convex dev. Convex Auth also needs JWT keys and SITE_URL on your deployment (see .env.local.example).",
      loading: "Loading…",
    },
    mainsUi: {
      intro:
        "Pick a GS paper, answer the drawn prompt, get feedback, then move to a fresh question. Scores count toward the leaderboard when you are signed in.",
      pickSubject: "Choose paper",
      questionLabel: "Question",
      answerLabel: "Your answer",
      marksLabel: "Max marks",
      marksHint: "UPSC commonly uses 10, 15, or 20 marks per question.",
      evaluate: "Evaluate answer",
      evaluating: "Evaluating…",
      feedbackTitle: "AI feedback",
      words: "Words",
      errorNoKey: "Server missing GROQ_API_KEY. Add it to .env.local and restart `npm run dev`.",
      errorGeneric: "Could not evaluate this answer. Try again.",
      sampleQuestion:
        "Discuss the role of the Finance Commission in strengthening fiscal federalism in India. (15 marks)",
      headingStructure: "Structure",
      headingContent: "Content depth",
      headingStrengths: "Strengths",
      headingImprovements: "Improvements",
      nextQuestion: "Next question",
      exhaustedTitle: "You have seen every prompt in this paper",
      exhaustedBody: "Pick another subject or revisit later as we expand the bank.",
      backToSubjects: "Back to papers",
      signInToSaveMains: "Sign in to add Mains marks to your leaderboard total.",
      loadingQuestions: "Loading prompts…",
    },
    dashboardUi: {
      sampleNote: "Your live stats from saved practice sessions.",
      readiness: "Prelims readiness",
      weeklyTrend: "Last 7 days accuracy (%)",
      heatmapTitle: "Accuracy by subject",
      recommendationsTitle: "Where to focus",
      weakTitle: "Subjects to strengthen",
      exportPdf: "Export report",
      exportSoon: "Coming soon",
      profileTitle: "Profile",
      profileHint:
        "Shown on the leaderboard. Handles can match other learners — the board shows a short ID when needed (letters, numbers, _).",
      displayName: "Display name",
      username: "Username",
      saveProfile: "Save profile",
      saving: "Saving…",
      saved: "Saved",
      signInForDashboard: "Sign in to view your dashboard and history.",
      historyTitle: "Recent tests",
      historyQuick: "10 Q",
      historyMock: "Mock",
      historyIncorrect: "Review wrong",
      noHistory: "No completed tests yet. Start from MCQ Practice.",
      streakLabel: "Day streak",
      subjects: [
        "Polity",
        "Economy",
        "History",
        "Geography",
        "Environment",
        "Science & Tech",
        "Art & Culture",
        "Current Affairs",
        "International Relations",
      ],
    },
    practiceUi: {
      subject: "Subject",
      topic: "Topic (optional)",
      topicPlaceholder: "e.g. Parliament",
      year: "Year",
      allYears: "All years",
      start: "Start practice",
      timedMock: "Timed mock (coming soon)",
      dataNote: "10-question subject drills and a 60-minute / 60-question mock. History syncs to your dashboard.",
      qLabel: "Question",
      check: "Check answer",
      next: "Next",
      finishTest: "Finish test",
      correct: "Correct",
      incorrect: "Incorrect",
      explanation: "Explanation",
      quickTitle: "Subject test (10 questions)",
      quickSubtitle: "Pick a paper. Questions are drawn at random from your bank for that subject.",
      mockTitle: "Full timed mock",
      mockSubtitle: "60 minutes · 60 questions · mixed subjects · no hints until the end",
      mockStart: "Start 60-minute mock",
      signInToPracticeTitle: "Sign in to practice",
      signInToPracticeBody:
        "Create a free account to run tests, save scores, update your streak, and see personalized analytics on your dashboard.",
      signInCta: "Sign in to continue",
      timeLeft: "Time left",
      questionProgress: "Question {n} of {t}",
      badgeQuick: "10 Q",
      badgeMock: "Mock",
      badgeIncorrect: "Wrong ×10",
      incorrectTitle: "Redo incorrect",
      incorrectSubtitle: "Ten questions you got wrong last time (latest attempt per question).",
      incorrectStart: "Do incorrect MCQ",
      noIncorrectYet: "No incorrect attempts to review yet. Finish a subject test first.",
      noIncorrectInBank: "Those questions are not in your current question bank (e.g. locale). Practice MCQs again.",
      resultsTitle: "Test complete",
      scorePercent: "{n}% accuracy",
      savedToDashboard: "Saved to your dashboard and leaderboard stats.",
      guestNoSave: "Results are not saved (offline / no account).",
      playAgain: "Play again",
      quitToMenu: "Back to menu",
      reviewTitle: "Review",
      smallBankHint:
        "Add more questions via Convex (seed or ingest) so each subject can always fill 10 questions.",
      configureConvexFallback: "Connect Convex (NEXT_PUBLIC_CONVEX_URL) to enable sign-in and saving.",
    },
    leaderboardUi: {
      title: "Leaderboard",
      description:
        "Ranked by total score: MCQs correct + Mains marks earned. Set a username on your dashboard to appear.",
      searchPlaceholder: "Search by username or name…",
      rank: "Rank",
      user: "Learner",
      correct: "MCQ ✓",
      mains: "Mains",
      total: "Total",
      attempted: "Attempted",
      streak: "Streak",
      empty: "No learners match your search.",
      loading: "Loading…",
    },
    chatUi: {
      placeholder: "Ask about syllabus, strategy, or current affairs…",
      send: "Send",
      thinking: "Thinking…",
      emptyTitle: "UPSC AI Mentor",
      emptyBody: "Ask anything UPSC-related. Answers use Groq; add Exa later for live web citations.",
      citations: "Sources",
      errorNoKey: "Add GROQ_API_KEY to .env.local and restart the dev server.",
      errorGeneric: "Could not get a reply. Try again.",
    },
    pages: {
      practice: {
        title: "MCQ Practice",
        description:
          "10-question subject drills and a 60-minute Prelims-style mock. Sign in to save scores, streaks, and analytics.",
        placeholder: "",
      },
      mains: {
        title: "Mains answer evaluation",
        description:
          "Write a feedback on structure, depth, keywords, and word limits — aligned to 10 / 15 / 20 markers.",
        placeholder: "",
      },
      dashboard: {
        title: "Performance dashboard",
        description:
          "Accuracy trends, subject heatmaps, time-per-question, weakness detection, and downloadable reports.",
        placeholder: "",
      },
      chat: {
        title: "UPSC AI Mentor",
        description:
          "Ask syllabus, strategy, and current-affairs questions. Responses use Groq with RAG over Exa-retrieved sources and official links.",
        placeholder: "",
      },
      leaderboard: {
        title: "Leaderboard",
        description: "Top learners by MCQ + Mains score. Search by username.",
        placeholder: "",
      },
    },
  },
  hi: {
    nav: {
      mcq: "MCQ अभ्यास",
      mains: "मेन्स मूल्यांकन",
      dashboard: "डैशबोर्ड",
      leaderboard: "लीडरबोर्ड",
      chat: "AI मार्गदर्शक",
    },
    authBanner: {
      title: "प्रगति सहेजने के लिए साइन इन करें",
      body: "स्कोर, स्ट्रीक, डैशबोर्ड और लीडरबोर्ड — सब एक खाते से।",
      cta: "साइन इन",
    },
    hero: {
      badge: "मुफ्त · AI-संचालित · हर उम्मीदवार के लिए",
      title: "UPSC तैयारी जो लाखों न लगे।",
      subtitle:
        "पिछले वर्षों के MCQ, Groq पर मेन्स उत्तर मूल्यांकन, स्ट्रीक, विश्लेषण, और RAG चैटबॉट — शून्य शुल्क, पूरी स्पष्टता।",
      ctaPrimary: "अभ्यास शुरू करें",
      ctaSecondary: "यह कैसे काम करता है",
    },
    features: {
      title: "वह सब जिसके लिए कोचिंग लाखों लेती है",
      items: [
        {
          title: "MCQ इंजन",
          body: "विषय, टॉपिक और वर्ष फ़िल्टर के साथ PYQ — समयबद्ध मॉक और स्रोतों के साथ तुरंत व्याख्या।",
        },
        {
          title: "मेन्स मूल्यांकन",
          body: "संरचना, गहराई, कीवर्ड और शब्द सीमा पर संरचित प्रतिक्रिया — 10/15/20 अंक योजना के अनुरूप।",
        },
        {
          title: "स्ट्रीक और XP",
          body: "दैनिक आदत, बैज और साप्ताहिक चुनौतियाँ ताकि निरंतरता चक्रवृद्धि की तरह बढ़े।",
        },
        {
          title: "प्रदर्शन डैशबोर्ड",
          body: "सटीकता रुझान, हीटमैप, प्रति प्रश्न समय, और AI कमजोर विषय पहचान।",
        },
        {
          title: "UPSC AI चैट",
          body: "Groq + Exa के साथ पाठ्यक्रम और करंट अफेयर्स — आधिकारिक लिंक के साथ उत्तर।",
        },
        {
          title: "आपका लर्निंग पथ",
          body: "परीक्षा भार × आपकी कमियों से साप्ताहिक योजना — स्मरण के लिए अंतराल।",
        },
      ],
    },
    bonus: {
      title: "भारत के लिए बना",
      ca: "दैनिक करंट अफेयर्स क्विज़",
      analyzer: "पिछले वर्षों के पेपर विश्लेषक",
      prompts: "दैनिक मेन्स लेखन प्रश्न",
      offline: "PWA ऑफ़लाइन MCQ",
      lang: "अंग्रेज़ी + हिंदी UI",
    },
    footer: "UPSCMENTOR — पहुँच सबके लिए। Convex · Groq · Apify · Exa।",
    signIn: "साइन इन",
    auth: {
      title: "साइन इन",
      subtitle: "ईमेल व पासवर्ड से, या Google से जारी रखें।",
      email: "ईमेल",
      password: "पासवर्ड",
      submitSignIn: "साइन इन",
      submitSignUp: "खाता बनाएँ",
      toggleToSignUp: "खाता नहीं है? साइन अप",
      toggleToSignIn: "पहले से खाता है? साइन इन",
      google: "Google से जारी रखें",
      signOut: "साइन आउट",
      configureConvex:
        ".env.local में NEXT_PUBLIC_CONVEX_URL सेट करें और npx convex dev चलाएँ। JWT keys और SITE_URL Convex डिप्लॉयमेंट पर चाहिए (.env.local.example देखें)।",
      loading: "लोड हो रहा है…",
    },
    mainsUi: {
      intro:
        "पेपर चुनें, दिया गया प्रश्न लिखें, Groq प्रतिक्रिया पाएँ, फिर नया प्रश्न। साइन इन पर अंक लीडरबोर्ड में जुड़ते हैं।",
      pickSubject: "पेपर चुनें",
      questionLabel: "प्रश्न",
      answerLabel: "आपका उत्तर",
      marksLabel: "अधिकतम अंक",
      marksHint: "UPSC में प्रायः 10, 15 या 20 अंक प्रति प्रश्न।",
      evaluate: "मूल्यांकन करें",
      evaluating: "मूल्यांकन हो रहा है…",
      feedbackTitle: "AI प्रतिक्रिया",
      words: "शब्द",
      errorNoKey: "सर्वर पर GROQ_API_KEY नहीं है। .env.local में जोड़कर `npm run dev` फिर चलाएँ।",
      errorGeneric: "मूल्यांकन नहीं हो सका। पुनः प्रयास करें।",
      sampleQuestion:
        "भारत में राजकोषीय संघवाद को मजबूत करने में वित्त आयोग की भूमिका पर चर्चा करें। (15 अंक)",
      headingStructure: "संरचना",
      headingContent: "विषयवस्तु",
      headingStrengths: "बल",
      headingImprovements: "सुधार",
      nextQuestion: "अगला प्रश्न",
      exhaustedTitle: "इस पेपर के सभी प्रश्न हो गए",
      exhaustedBody: "दूसरा विषय चुनें या बैंक बढ़ने पर लौटें।",
      backToSubjects: "पेपर पर वापस",
      signInToSaveMains: "लीडरबोर्ड में मेन्स अंक जोड़ने के लिए साइन इन करें।",
      loadingQuestions: "प्रश्न लोड हो रहे हैं…",
    },
    dashboardUi: {
      sampleNote: "आपके सहेजे गए सत्रों से लाइव आँकड़े।",
      readiness: "प्रीलिम्स तैयारी",
      weeklyTrend: "पिछले 7 दिन सटीकता (%)",
      heatmapTitle: "विषयवार सटीकता",
      recommendationsTitle: "ध्यान कहाँ दें",
      weakTitle: "मजबूत करने वाले विषय",
      exportPdf: "रिपोर्ट निर्यात",
      exportSoon: "जल्द",
      profileTitle: "प्रोफ़ाइल",
      profileHint:
        "लीडरबोर्ड पर दिखेगा। दो लोग एक जैसा नाम रख सकते हैं — ज़रूरत पड़ने पर छोटा ID दिखाया जाएगा (अक्षर, संख्या, _)।",
      displayName: "नाम",
      username: "उपयोगकर्ता नाम",
      saveProfile: "सहेजें",
      saving: "सहेज रहे हैं…",
      saved: "सहेजा गया",
      signInForDashboard: "डैशबोर्ड और इतिहास के लिए साइन इन करें।",
      historyTitle: "हाल के टेस्ट",
      historyQuick: "10 प्रश्न",
      historyMock: "मॉक",
      historyIncorrect: "गलत दोहराएँ",
      noHistory: "अभी कोई टेस्ट पूरा नहीं। MCQ अभ्यास से शुरू करें।",
      streakLabel: "दिन की स्ट्रीक",
      subjects: [
        "राजनीति",
        "अर्थव्यवस्था",
        "इतिहास",
        "भूगोल",
        "पर्यावरण",
        "विज्ञान व प्रौद्योगिकी",
        "कला व संस्कृति",
        "सामयिकी",
        "अंतरराष्ट्रीय संबंध",
      ],
    },
    practiceUi: {
      subject: "विषय",
      topic: "टॉपिक (वैकल्पिक)",
      topicPlaceholder: "जैसे संसद",
      year: "वर्ष",
      allYears: "सभी वर्ष",
      start: "अभ्यास शुरू करें",
      timedMock: "समयबद्ध मॉक (जल्द)",
      dataNote: "10 प्रश्नीय विषय टेस्ट और 60 मिनट / 60 प्रश्न मॉक। इतिहास डैशबोर्ड पर सिंक होगा।",
      qLabel: "प्रश्न",
      check: "उत्तर जाँचें",
      next: "आगे",
      finishTest: "टेस्ट समाप्त",
      correct: "सही",
      incorrect: "गलत",
      explanation: "व्याख्या",
      quickTitle: "विषय टेस्ट (10 प्रश्न)",
      quickSubtitle: "पेपर चुनें। प्रश्न उस विषय के बैंक से यादृच्छिक आएंगे।",
      mockTitle: "पूर्ण समयबद्ध मॉक",
      mockSubtitle: "60 मिनट · 60 प्रश्न · मिश्रित विषय · अंत तक संकेत नहीं",
      mockStart: "60-मिनट मॉक शुरू करें",
      signInToPracticeTitle: "अभ्यास के लिए साइन इन",
      signInToPracticeBody:
        "मुफ्त खाता बनाएँ — टेस्ट, स्कोर, स्ट्रीक और व्यक्तिगत विश्लेषण सहेजें।",
      signInCta: "जारी रखने के लिए साइन इन",
      timeLeft: "शेष समय",
      questionProgress: "प्रश्न {n} / {t}",
      badgeQuick: "10 प्रश्न",
      badgeMock: "मॉक",
      badgeIncorrect: "गलत ×10",
      incorrectTitle: "गलत फिर से",
      incorrectSubtitle: "वे 10 प्रश्न जो पिछली बार गलत हुए (प्रति प्रश्न नवीनतम प्रयास)।",
      incorrectStart: "गलत MCQ करें",
      noIncorrectYet: "अभी दोहराने के लिए कोई गलत प्रयास नहीं। पहले विषय टेस्ट पूरा करें।",
      noIncorrectInBank: "वे प्रश्न वर्तमान बैंक में नहीं (जैसे भाषा)। फिर से MCQ अभ्यास करें।",
      resultsTitle: "टेस्ट पूर्ण",
      scorePercent: "{n}% सटीकता",
      savedToDashboard: "डैशबोर्ड और लीडरबोर्ड पर सहेजा गया।",
      guestNoSave: "परिणाम सहेजे नहीं गए।",
      playAgain: "फिर खेलें",
      quitToMenu: "मेनू पर वापस",
      reviewTitle: "समीक्षा",
      smallBankHint: "Convex में और प्रश्न जोड़ें ताकि हर विषय में 10 प्रश्न मिल सकें।",
      configureConvexFallback: "साइन इन व सहेजने के लिए Convex कनेक्ट करें (NEXT_PUBLIC_CONVEX_URL)।",
    },
    leaderboardUi: {
      title: "लीडरबोर्ड",
      description:
        "कुल स्कोर: सही MCQ + मेन्स अंक। डैशबोर्ड पर उपयोगकर्ता नाम सेट करें।",
      searchPlaceholder: "उपयोगकर्ता नाम या नाम खोजें…",
      rank: "रैंक",
      user: "छात्र",
      correct: "MCQ ✓",
      mains: "मेन्स",
      total: "योग",
      attempted: "प्रयास",
      streak: "स्ट्रीक",
      empty: "कोई मेल नहीं।",
      loading: "लोड हो रहा है…",
    },
    chatUi: {
      placeholder: "पाठ्यक्रम, रणनीति या करंट अफेयर्स पूछें…",
      send: "भेजें",
      thinking: "सोच रहा है…",
      emptyTitle: "UPSC AI मार्गदर्शक",
      emptyBody: "UPSC से जुड़ा कुछ भी पूछें। उत्तर Groq से; बाद में Exa से लाइव स्रोत।",
      citations: "स्रोत",
      errorNoKey: ".env.local में GROQ_API_KEY जोड़कर सर्वर फिर चलाएँ।",
      errorGeneric: "उत्तर नहीं मिला। पुनः प्रयास करें।",
    },
    pages: {
      practice: {
        title: "MCQ अभ्यास",
        description:
          "10 प्रश्नीय विषय टेस्ट और 60 मिनट का मॉक। स्कोर व स्ट्रीक सहेजने के लिए साइन इन करें।",
        placeholder: "",
      },
      mains: {
        title: "मेन्स उत्तर मूल्यांकन",
        description:
          "PYQ पर लिखें और Groq से संरचना, गहराई, कीवर्ड व शब्द सीमा पर प्रतिक्रिया पाएं — 10/15/20 अंकों के अनुरूप।",
        placeholder: "",
      },
      dashboard: {
        title: "प्रदर्शन डैशबोर्ड",
        description:
          "सटीकता, विषय हीटमैप, समय विश्लेषण, कमजोर विषय — Convex में आपके इतिहास से।",
        placeholder: "",
      },
      chat: {
        title: "UPSC AI मार्गदर्शक",
        description:
          "पाठ्यक्रम, रणनीति और करंट अफेयर्स — Groq + Exa स्रोतों और आधिकारिक लिंक के साथ।",
        placeholder: "",
      },
      leaderboard: {
        title: "लीडरबोर्ड",
        description: "MCQ + मेन्स स्कोर से शीर्ष छात्र। उपयोगकर्ता नाम से खोजें।",
        placeholder: "",
      },
    },
  },
} as const;

export type PracticeUiCopy = (typeof landingCopy)[Locale]["practiceUi"];
export type PracticePageCopy = (typeof landingCopy)[Locale]["pages"]["practice"];
